# Generated by Django 5.1.6 on 2025-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund')], default='unknown', max_length=10),
        ),
    ]
