# Generated by Django 5.1.6 on 2025-02-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_transaction_status_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('paystack', [('name', 'Paystack'), ('min_amount', 1000), ('max_amount', 10000000)]), ('flutterwave', [('name', 'Flutterwave'), ('min_amount', 1000), ('max_amount', 10000000)])], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
