# Generated by Django 5.1.6 on 2025-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('wallet', 'Wallet')], default='unknown', max_length=20),
        ),
    ]
