# Generated by Django 5.1.6 on 2025-02-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('wallet', 'Wallet')], default='unknown', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund')], default='unknown', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.wallet'),
        ),
    ]
