# Generated by Django 5.1.6 on 2025-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
