# Generated by Django 5.1.6 on 2025-03-11 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transaction_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet'),
        ),
    ]
