# Generated by Django 4.2.20 on 2025-05-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_transaction_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('korapay', 'Korapay'), ('wallet', 'Wallet'), ('manual', 'Manual Transfer')], default='unknown', max_length=20),
        ),
    ]
