# Generated by Django 5.1.6 on 2025-02-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_socialmediaaccount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not Verified'), ('pending', 'Pending')], max_length=12),
        ),
    ]
