# Generated by Django 5.1.6 on 2025-02-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_socialmediaaccount_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='account_age',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
