# Generated by Django 5.1.6 on 2025-02-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_socialmediaaccount_account_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='account_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], max_length=20),
        ),
    ]
