# Generated by Django 5.1.6 on 2025-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_socialmediaaccount_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
