# Generated by Django 5.1.6 on 2025-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_socialmediaaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
