# Generated by Django 5.1.6 on 2025-02-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_remove_socialmediaaccount_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='social_media',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('vpn', 'VPN'), ('tools', 'Tools'), ('email', 'Email'), ('streaming', 'Streaming')], max_length=20),
        ),
    ]
