# Generated by Django 5.1.6 on 2025-02-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_socialmediaaccount_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
