# Generated by Django 5.1.6 on 2025-02-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_socialmediaaccount_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='followers_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The number of followers on the account.', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='following_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The number of following on the account.', null=True),
        ),
    ]
