# Generated by Django 5.1.6 on 2025-02-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_alter_socialmediaaccount_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='category',
        ),
        migrations.DeleteModel(
            name='AccountCategory',
        ),
    ]
