# Generated by Django 5.1.6 on 2025-02-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_remove_socialmediaaccount_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='account_age',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('not_verified', 'Not Verified'), ('pending', 'Pending')], max_length=12, null=True),
        ),
    ]
