# Generated by Django 5.1.6 on 2025-02-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='order_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketplace.orderitem'),
        ),
    ]
