# Generated by Django 4.2.20 on 2025-05-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_category_socialmediaaccount_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
