# Generated by Django 4.2.20 on 2025-05-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='social_media',
        ),
    ]
