# Generated by Django 4.2.20 on 2025-05-31 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_category_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'pk'], 'verbose_name_plural': 'Categories'},
        ),
    ]
