# Generated by Django 4.2.20 on 2025-06-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_socialmediaaccount_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediaaccount',
            options={'ordering': ['position', 'position_created_at']},
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='position_updated_at',
        ),
    ]
